tests: Fix clippy::needless_maybe_sized warning
```
error: `?Sized` bound is ignored because of a `Sized` requirement
   --> tests/test.rs:279:12
    |
279 |         T: ?Sized,
    |            ^^^^^^
    |
note: `T` cannot be unsized because of the bound
   --> tests/test.rs:280:12
    |
280 |         T: Default,
    |            ^^^^^^^
    = note: ...because `Default` has the bound `Sized`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_maybe_sized
    = note: `-D clippy::needless-maybe-sized` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::needless_maybe_sized)]`
help: change the bounds that require `Sized`, or remove the `?Sized` bound
    |
279 -         T: ?Sized,
    |
```